server:
  port: 8080

spring:
  application:
    name: gestionPersonal

  datasource:
    url: jdbc:mysql://localhost:3306/financiera?severTimezone=America/Bogota
    #url: jdbc:mysql://root:QheksigHMZofgVGmMPnBVRzuXJRIUlXe@tramway.proxy.rlwy.net:47256/railway
    username: root              # Cambia esto por tu usuario de MySQL
    password: admin       # Cambia esto por tu contraseña de MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect