server:
  port: 8080

spring:
  application:
    name: gestionPersonal

  datasource:
    url: jdbc:mysql://localhost:3306/davivienda?severTimezone=America/Bogota

    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect